### ISSUE TITLE
bugfix: helpコマンドキャメルケースになっている

### ISSUE THREAD

**Issue by y1wtt** [waiwai-developers/waiwaichan#136]
pull req: [Fix command name #149](https://github.com/waiwai-developers/waiwaichan/pull/149)

**Comment by mamepon2580** [comment]
## 検証結果

- /helpコマンド
  - /helpコマンドを実行したとき
    - [ ] `/pointcheck`と表示されること
    - [ ] `/pointdraw`と表示されること
    - [ ] `/pointitem`と表示されること

**Comment by mamepon2580** [comment]
<img width="1728" alt="スクリーンショット 2024-11-12 19 05 25" src="https://github.com/user-attachments/assets/50e03479-dba3-436c-80c8-c580abf32b86">
