### ISSUE TITLE
feature: pointという名前が可愛くないのでcandyに変えたい

### ISSUE THREAD

**Issue by mamepon2580** [waiwai-developers/waiwaichan#176]
- #361

**Comment by y1wtt** [comment]
ついでにchangeもexchangeに変えたいですね

**Comment by mamepon2580** [comment]
## 検証項目

- pointコマンド
  - ポイント付与機能の場合
    - configに設定されているスタンプを日付を基準に1日以内に3回以下で他人の投稿に押した時
      - [x] 「@〇〇さんが××スタンプを押したよ！！っ」というメッセージのリプライが投稿されていること
    - cconfigに設定されているスタンプを基準に1日以内3回に以下botの投稿に押した時
      - [x] 「@〇〇さんが××スタンプを押したよ！！っ」というメッセージのリプライが投稿されてないこと
    - configに設定されているスタンプを基準に1日以内3回に以下で自分の投稿に押した時
      - [x] 「@〇〇さんが××スタンプを押したよ！！っ」というメッセージのリプライが投稿されてないこと
    - configに設定されているスタンプを基準に1日以内に3回より多くで他人の投稿に押した時
      - [x] 「今はスタンプを押してもポイントをあげられないよ！っ」というメッセージのリプライが投稿されてないこと
  - /pointcheckの場合
    - ポイントがある場合に/pointcheckを実行した時
      - [x] 「〇〇ポイントあるよ！っ」というメッセージのリプライが投稿されてないこと
    - ポイントがない場合に/pointcheckを実行した時
      - [x] 「ポイントがないよ！っ」というメッセージのリプライが投稿されてないこと
  - /pointdrawの場合
    - ポイントがある場合に/pointdrawを実行した時
      - [x] 「ハズレちゃったよ！っ」または「〇〇が当たったよ🍭！っ」というメッセージのリプライが投稿されていること
    - ポイントがない場合に/pointdrawを実行した時
      - [x] 「ポイントがないよ！っ」というメッセージのリプライが投稿されていること
  - /pointitemの場合
    - アイテムがある場合に/pointitemを実行した時
      - [x] 「以下のアイテムが交換できるよ！っ」というメッセージのリプライが投稿されていること
    - アイテムがない場合に/pointitemを実行した時
      - [x] 「アイテムは持ってないよ！っ」というメッセージのリプライが投稿されていること
  - /pointChangeの場合
    - アイテムがある場合にidパラメータで「itemId」を入力し/pointChangeを実行した時
      - [x] 「アイテムは持ってないよ！っ」というメッセージのリプライが投稿されていること
    - アイテムがない場合にidパラメータで「itemId」を入力し/pointChangeを実行した時
      - [x] 「〇〇と交換したよ！っ」というメッセージのリプライが投稿されていること
