### ISSUE TITLE
feature: pnpm or yarn or npmを決める

### ISSUE THREAD

**Issue by y1wtt** [waiwai-developers/waiwaichan#198]
## やること
- 決める
- lockfileをcommitする

**Comment by y1wtt** [comment]
@mamepon2580 @wautopia 
これさっさと決めちゃいたんですが、パッケージ管理は何使ってます？
ちなみに僕は `pnpm` を推したいです

**Comment by wautopia** [comment]
npmです！折角の機会なのでnpm以外のものでも大丈夫です！

**Comment by mamepon2580** [comment]
@y1wtt 
pnpmで結論いいと思うのですがそれぞれのメリットとドキュメントのリンク貼っておいて頂けると！

**Comment by y1wtt** [comment]
## なぜPNPMを使うのか
- npm互換である (yarnはnpm互換コマンドではない)
- シンボリックリンクを利用することで、ディスク容量を減らすことができる
    - 同バージョンの同一ライブラリは2度インストールされない
    - npmはこれが発生する
- 速い
    -  npmは依存関係の依存関係を再帰的にインストールする
        - ディレクトリのネストが深くなってアクセスが遅くなる
- yarnとの違い
    - yarnはnpmの問題をすべてトップレベルにパッケージをインストールし解決する
    - つまり、依存関係の依存関係がトップレベルからアクセスできる＝隠蔽できていない (Phantom dependencies)
    - pnpmでは安全かつ高速に依存関係を隠蔽できる
