### ISSUE TITLE
feature: Node.jsでコンパイルせずにTypeScriptを利用したい

### ISSUE THREAD

**Issue by mamepon2580** [waiwai-developers/waiwaichan#204]
# pull req

- [Feature/add type #181](https://github.com/waiwai-developers/waiwaichan/pull/181)

**Comment by y1wtt** [comment]
@mamepon2580 
今回導入したtsxというのは**JSXのTS版ではなく**TypeScript Executeという、Node.jsのTS拡張です。
主にdevサーバーで実行するために使います。
