### ISSUE TITLE
feature: Cloud Buildでgithub上でmain mergeした時にArtifact Registryにimageをbuildするようにしたい

### ISSUE THREAD

**Issue by mamepone** [waiwai-developers/waiwaichan#218]
- #217

**Comment by mamepon2580** [comment]
<img width="1675" alt="スクリーンショット 2024-11-21 23 13 07" src="https://github.com/user-attachments/assets/a7616713-aaae-4436-814c-7be73d47e2f1">
<img width="1677" alt="スクリーンショット 2024-11-21 23 13 46" src="https://github.com/user-attachments/assets/86ffca17-741d-4da0-bac9-fc2a84f271c5">
