### ISSUE TITLE
ポイント付与上限の条件がミスっている 

### ISSUE THREAD

**Issue by y1wtt** [waiwai-developers/waiwaichan#270]

**Comment by mamepon2580** [comment]
📝 memo

code read
- `src\routes\discordjs\events\ReactionRouter.ts line 48`
- `src\logics\Interfaces\logics\IPointLogic.ts` line 13
- `src\logics\PointLogic.ts` line 127
- `src\repositories\sequelize-mysql\PointRepositoryImpl.ts` line 40

fix Content
- PointRepositoryImplの引き方をcreatedatに修正
